### ISSUE TITLE
Guide to getting it to work

### ISSUE THREAD

**Issue by juanaldreagan** [alixaxel/chrome-aws-lambda#11]
I've tried running:
 
npm pack && \
mkdir --parents nodejs/node_modules/chrome-aws-lambda/ && \
tar --directory nodejs/node_modules/chrome-aws-lambda/ --extract --file chrome-aws-lambda-*.tgz --strip-components=1 && \
rm chrome-aws-lambda-*.tgz && \
zip -9 --filesync --move --recurse-paths _/chrome-aws-lambda.layer.zip nodejs/

on AWS linux AMI, Ubuntu, and Mac OS and cannot get this work. Likely due to my understanding of node but really love the idea of the project and would like to implement!

**Comment by alixaxel** [comment]
@juanaldreagan I can see how that could be confusing for a newcomer.

I've [moved the AWS Lambda Layer section down and updated instructions](https://github.com/alixaxel/chrome-aws-lambda/blob/master/README.md#aws-lambda-layer) so that it's not featured as prominently. But if you don't know what Lambda Layers are and you just want to use the package, just check out the[ Install & Usage](https://github.com/alixaxel/chrome-aws-lambda#install) sections of the README, that should get you started.
