### ISSUE TITLE
Works on lambda but not SAM local

### ISSUE THREAD

**Issue by ToddHoff** [alixaxel/chrome-aws-lambda#12]
I'm able to convert some html to PDF and it works fine under lambda, but when I test on my machine using SAM local it gives:

Error:
Failed to load PDF document.

The code is:

```
try {
      browser = await Puppeteer.launch({
         args          : Chromium.args,
         executablePath: await Chromium.executablePath,
         headless      : Chromium.headless
      });

      const page = await browser.newPage();
      await page.goto(`data:text/html,${html}`, {waitUntil: 'networkidle0'});
      await page.pdf({path: "/tmp/file.pdf", format: 'A4'});
      await browser.close();

   } catch (error) {
      throw error;
   } finally {
      if (browser !== null) {
         await browser.close();
      }
   }
```

Any ideas why it might not be working? I don't see any obvious errors.

**Comment by alixaxel** [comment]
@ToddHoff I'm not very familiar with SAM execution model, but I suspect one possible reason might be that the Chromium binary is not compatible with your system? Again, I have no clue how SAM local operates.

I shared instructions over here for how to https://github.com/alixaxel/chrome-aws-lambda/issues/7#issuecomment-450402988 conditionally require puppeteer for testing purposes.

If that turns out not to be the case, would you mind sharing reproducible steps so I can look into it?

**Comment by ToddHoff** [comment]
SAM local is a complicated beast so I'm not all that sure how it works either. I was able to get get puppeteer working under node on my local machine, so I know it works in general, it's just that you can't upload all that to lambda. 

I'll definitely take a look at your testing instructions. The image issue makes a lot of sense. Thanks!

**Comment by yoanisgil** [comment]
@ToddHoff I was able to make this run by making sure that the function is built inside a container.
