### ISSUE TITLE
[BUG] Fails to import into a Typescript module

### ISSUE THREAD

**Issue by willdady** [alixaxel/chrome-aws-lambda#122]
## Environment
* `chrome-aws-lambda` Version: 2.1.1
* `puppeteer` / `puppeteer-core` Version: 3.0.1
* OS: Linux Mint
* Node.js Version: 13.12.0
* Lambda / GCF Runtime: N/A

## Expected Behavior
Ideally should be able to import into a Typescript module without error.

## Current Behavior
Importing into a typescript file fails to compile. Yields the following error:

```
node_modules/chrome-aws-lambda/source/index.d.ts:1:106 - error TS2307: Cannot find module 'puppeteer'.
```
Note I've followed the instructions in the README and only installed `puppeteer-core`.

**Comment by havryliv** [comment]
+1. Is there any workaround of this?

**Comment by alixaxel** [comment]
@willdady This is caused by my failed attempt at providing the overloaded typings:

https://github.com/alixaxel/chrome-aws-lambda/blob/7e4f2c08c665307036f2472387d7eefde7904fab/source/index.d.ts#L1

https://github.com/alixaxel/chrome-aws-lambda/blob/7e4f2c08c665307036f2472387d7eefde7904fab/package.json#L25-L27

I'm not really sure how to go about fixing this...

The newest version of puppeteer is transitioning to TypeScript, but only `src/` is covered for now.

Even when puppeteer fully transitions to TS, they will still publish two packages: `puppeteer` and `puppeteer-core`, which one to import from (given that I can only list one as a `peerDependency`).

For now the recommendation is still to use `@types/puppeteer`:

![image](https://user-images.githubusercontent.com/262782/81462600-a6acd080-91ab-11ea-9f69-7770ff3d100a.png)

I will have a go at replacing the import with a [triple slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-) tomorrow.

**Comment by alixaxel** [comment]
Related: #114

**Comment by G-Rath** [comment]
I'm able to import this into my TypeScript project without problem, using `@types/puppeteer-core`.

Would you be able to provide a reproduction repo for me to play with?

In general, the typings should import from puppeteer, as `@types/puppeteer-core` is actually just an alias of `@types/puppeteer` (its literally just `export * from "puppeteer";`) so `@types/puppeteer` will always be installed if you use either package.

The peerDependency should be on `puppeteer-core`, as that is the opposite way around: `puppeteer` requires `puppeteer-core`, so `puppeteer-core` will always be satisfied regardless of which one you use.

**Comment by benlongmire** [comment]
Related: https://github.com/alixaxel/chrome-aws-lambda/issues/156

I have opened another pull request for latest version of puppeteer. I'd be keen to help out with this if you can point me in the right direction.
