### ISSUE TITLE
[BUG] Unable to retrieve all cookies with puppeteer-core and chrome-aws-lambda

### ISSUE THREAD

**Issue by nthanhhai** [alixaxel/chrome-aws-lambda#140]
First of all, I wasn't sure whether it's specific to chrome-aws-lambda. I've compared it with puppeteer and chromium binary comes with it and it was working fine. I just have issue when using chrome-aws-lambda so thinking here maybe able to resolve or provide suggestions.

## Environment
* `chrome-aws-lambda` Version: 3.1.1
* `puppeteer` / `puppeteer-core` Version: 3.1.0/3.2.0
* OS: MacOS Catalina
* Node.js Version: 10.x
* Lambda / GCF Runtime: nodejs10.x

## Expected Behavior
page.cookies() should be able to return all cookies of that page.

## Current Behavior
Not all cookies are returned. I've compared it with puppeteer and chromium version which come with puppeteer and navigate to github.com.

`puppeteer` returns 6 cookies
```js
cookie: tz
cookie: _gat
cookie: logged_in
cookie: _octo
cookie: _ga
cookie: _gh_sess
```

`puppeteer-core + chrome-aws-lambda` returns 5 cookies
```js
cookie: _gh_sess
cookie: _octo
cookie: logged_in
cookie: _ga
cookie: tz
```

The above is just an example of getting cookies. My actual application have more than 40 cookies and puppeteer-core + chrome-aws-lambda are able to retrieve 22 - 24 cookies.

I've also tried to retrieve cookies using CDP commands
```js
await client.send('Network.getAllCookies'))
```
but still also not able to retrieve all cookies.

## Steps to Reproduce

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page = await browser.newPage();

    await page.goto('https://github.com', { waitUntil: 'networkidle0' });

    const cookies = await page.cookies();
    cookies.forEach((cookie) => {
      console.log('cookie: ' + cookie['name']);
    });
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

**Comment by alixaxel** [comment]
@nthanhhai I was able to trace the missing cookie from browser sniffing on `navigator.plugins`:

![image](https://user-images.githubusercontent.com/262782/84457247-122a0800-ac5a-11ea-9a7c-e899ef7c7eff.png)

I'm doing some basic sanitization [to](https://gist.github.com/tegansnyder/c3aeae4d57768c58247ae6c4e5acd3d1) [avoid](https://intoli.com/blog/making-chrome-headless-undetectable/) [detection](https://antoinevastel.com/bot%20detection/2018/01/17/detect-chrome-headless-v2.html):

https://github.com/alixaxel/chrome-aws-lambda/blob/954ddb8989abf832a96f9f3586efd6e5ed7f2ca1/source/puppeteer/lib/Browser.js#L24-L39

However, it seems that the plugins hack is no longer necessary, so I will run some tests and consider removing it in the upcoming version. In the meantime, you can avoid the overloads:

```ts
import * as puppeteer from 'puppeteer-core';
import * as chromium from 'chrome-aws-lambda';
// ...
browser = await puppeteer.launch(...)
```

Instead of:

```ts
import * as chromium from 'chrome-aws-lambda';
// ...
browser = await chromium.puppeteer.launch(...)
```

**Comment by nthanhhai** [comment]
Thanks @alixaxel. I will give it a try and will let you know the result.

**Comment by nthanhhai** [comment]
@alixaxel I've used the method you suggested and it's working for my purpose. Thanks.
