### ISSUE TITLE
[BUG] Unable to capture screenshot

### ISSUE THREAD

**Issue by ilhamilo08** [alixaxel/chrome-aws-lambda#159]
## Environment
* `chrome-aws-lambda` Version: 3.1.1
* `puppeteer-core` Version: 3.1.0
* OS: 
* Node.js Version: 12.x
* Lambda : `nodejs12.x`

## Expected Behavior
Can successfully capture https://alas.aws.amazon.com/ and https://kb.wpbakery.com/docs/preface/release-notes/

## Current Behavior
Error: Protocol error (Page.captureScreenshot): Unable to capture screenshot. 

The page.content() is able to get the html document but page.screenshot({ encoding: 'binary', fullPage: true }) returns the error above but if fullpage is set false, it can capture some part of the webpage.

**Comment by alixaxel** [comment]
@ilhamilo08 I suspect the problem is that since those pages are super long, capturing a screenshot of the `fullPage` will consume more memory to build the intermediary image data than what you have provisioned (or is available on Lambda).

I suggest to try to capture multiple sections of the page and a time and then stitch them up together at the end.

**Comment by StephenLover** [comment]
@alixaxel I am experiencing the same error occasionally, is there any way to fix this?

0|index    | Error: Error: Protocol error (Page.captureScreenshot): Unable to capture screenshot
0|index    |     at captureScreenshot (/home/ubuntu/puppeteer-recorder.js:26:13)
0|index    |     at <anonymous>
0|index    |     at process._tickDomainCallback (internal/process/next_tick.js:229:7)

![Screen Shot 2020-10-08 at 10 27 36 am](https://user-images.githubusercontent.com/18587261/95398199-e6d9d000-0950-11eb-8bd0-6347ae75b48d.png)
