### ISSUE TITLE
add a bin to create a layer?

### ISSUE THREAD

**Issue by pocesar** [alixaxel/chrome-aws-lambda#17]
the AWS layer instructions are convoluted and doesn't work on Windows, so what about creating a bin that could be executed from npm `scripts` section? like `chrome-aws-lambda create-layer` or just `chrome-aws-lambda` that puts the proper zip inside `./layer`. this would automatically make it cross platform

**Comment by pavelloz** [comment]
I dont know if that will help, but on OSX i had to modify that line:

> mkdir --parents nodejs/node_modules/chrome-aws-lambda/ && \

to the shortcut version of --parents

> mkdir -p nodejs/node_modules/chrome-aws-lambda/ && \

Because it was throwing me an error.

**Comment by alixaxel** [comment]
@pavelloz Thanks, I usually prefer long arguments over short ones for scripts/documentation (for clarity) but I will change that one so that it's also compatible with OSX - I assume all the other ones work fine?

@pocesar A cross-platform executable to create the layer would likely require more dependencies. Besides, I don't own a Windows machine so it would be hard for me to attempt that. If you find a equivalent set of commands for Windows, feel free to share and I'll update the README.
