### ISSUE TITLE
Is puppeteer-core / puppeteer installed with chrome-aws-lambda

### ISSUE THREAD

**Issue by pavelloz** [alixaxel/chrome-aws-lambda#19]
Hello,

Thanks for your work on this, saved me a lot of time already :)

Im using chrome-aws-lambda in a layer, i was wondering if I have to install puppeteer-core separately?

If i dont install it separately on my lambda, it doesnt find puppeteer-core, but i can see it in chrome-aws-lambda dependencies, so i was just wondering if im doing something wrong.

My concern is that those dependencies can desynchronize and as you probably know, any puppeteer version if guaranteed to work only with certain chromium version (more on that here: https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy ) - thats why im trying to invent a way to avoid breaking it when i update one and forget about the other.

Thanks,
Pawel

**Comment by hisham** [comment]
+1. It seems puppeteer-core is only a devDependency to this package so you should install yourself.

**Comment by alixaxel** [comment]
@pavelloz No, it's not. This project started before `puppeteer-core` was released and with standard `puppeteer` additional tweaking was necessary to prevent the download of the default binary.

I'm not sure if `puppeteer-core` should be bundled tho, as that can become kinda restrictive. Even listing it in `peerDependencies` in this case is not ideal, as you may still prefer to use `puppeteer` (for local testing).

**Comment by pavelloz** [comment]
Any thoughts on https://github.com/GoogleChrome/puppeteer#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy ?

**Comment by alixaxel** [comment]
@pavelloz To put it in PPTR terms: I see `chrome-aws-lambda` as a **divisible entity** of `puppeteer` / `puppeteer-core` (the simple fact that there's two puppeteer packages kinda mandates that).

As in, you could use the `executablePath` getter to get a binary that you could use with other libraries, like [CRI](https://github.com/cyrus-and/chrome-remote-interface) for instance. The fact that there are puppeteer-specific helper methods within this package is merely a acknowledgment that PPTR is the de-facto library for Chrome interaction, but not necessarily the only one.

I started this project following Chromium version numbers as release tags, but soon switched to puppeteer versions in order to make it easier for users to sync puppeteer and chrome-aws-lambda dependencies.

Any major/minor version of puppeteer will have a corresponding major/minor version of chrome-aws-lambda (patch number is reserved to fix issues in this package). To me, that seems simple enough to keep in sync.

**Comment by alixaxel** [comment]
There's a few more reasons why I think bundling is a bad idea, the first of which I already mentioned: `chrome-aws-lambda` started before `puppeteer-core` was released, so that would mean if `puppeteer-core` was bundled now, backwards expectations would fail.

Another one is that I'd have a lot more overhead following puppeteer releases: 3 patch versions of puppeteer were released in the last 9 days, but they all kept the same Chromium version. So far, all Chromium version bumps have been followed by a minor version bump, but that might not always be the case, so tracking that with semver could become very manual.

Another reason is drifts in versions that would just create confusion; puppeteer 1.11.0 was followed by chrome-aws-lambda 1.11.0, but there would have unmatched versions with upstream:

- chrome-aws-lambda 1.11.1 introduced typings and a minor improvement
- chrome-aws-lambda 1.11.2 introduced support for Google Cloud Functions
