### ISSUE TITLE
[BUG] Timezone switches between GMT and UTC after first invocation

### ISSUE THREAD

**Issue by tmeasday** [alixaxel/chrome-aws-lambda#199]
## Environment
* `chrome-aws-lambda` Version: 5.1.0
* `puppeteer` / `puppeteer-core` Version: 5.1.0
* OS: Mac
* Node.js Version: 12.x
* Lambda / GCF Runtime: `nodejs12.x`

I reproduced with 5.1.0 as that's the version we are on but I'm pretty confident it will be there in latest.

## Expected Behavior

Consistent timezones reported by browser

## Current Behavior

For a "preserved" lambda, the first call will report the timezone as "GMT", subsequent calls will report "UTC".

Switching TZs leads to inconsistent screenshots for any test cases that use TZ formatting.

## Steps to Reproduce

This repository shows the issue -- you can deploy to lambda to see the problem:

https://github.com/chromaui/test-puppeteer-tz/blob/master/package.json

The basic code is very simple:

https://github.com/chromaui/test-puppeteer-tz/blob/c8b9cb26b74ace995b823664c27f38b110b87a26/index.js#L9-L17

What happens (I can submit a video if it helps):

 - the first call the lambda, it logs a time with "GMT" at the end. This "first" call is pretty obvious as it takes the lambda instance a moment to un-brotli the chromium file.
 - Subsequent calls will report the TZ as "UTC".

## Possible Solution

The reason for the bug is the `if (timezone === null)` here: 

https://github.com/alixaxel/chrome-aws-lambda/blob/fa331bf0c83d52e4c51270eca15dd79bafba6a21/source/puppeteer/lib/Browser.js#L23-L30

I'm not sure what the idea there is, it was included in a large (squash) commit without explanation, so I'm not sure what the purpose was 🤷 

## Workaround

If you don't import `puppeteer` from `chrome-aws-lambda` it won't run this code.

**Comment by alixaxel** [comment]
@tmeasday Thanks for the report, I will look into this shortly.

**Comment by alixaxel** [comment]
@tmeasday So the bug was a typical one, I was storing the `timezone` variable outside of the function execution context, which caused it to be remembered across multiple Lambda executions and only triggering the actual emulation on cold starts. 🤦 

With version 8.0.0 (just released) I introduced some breaking changes to the overloading logic, namely:

1. Importing `puppeteer` of `chrome-aws-lambda` will only [enrich the underlying `puppeteer` API](https://github.com/alixaxel/chrome-aws-lambda/tree/v8.0.0#overloading), no in-page side effects.
2. Potential in-page side effects have to be [cherry-picked](https://github.com/alixaxel/chrome-aws-lambda/tree/v8.0.0/source/hooks) and handled by [page hooks](https://github.com/alixaxel/chrome-aws-lambda/tree/v8.0.0#page-hooks).

Your original example would now read something like this (if timezone emulation is desired, of course):

```javascript
const { executablePath, puppeteer } = require('chrome-aws-lambda');
const emulateTimezone = require('chrome-aws-lambda/build/hooks/timezone');

const index = async (event, context, callback) => {
  const browser = await puppeteer.launch({
    // args,
    executablePath: await executablePath,
  });

  const page = await browser.newPage(emulateTimezone);

  await page.goto('https://jsbin.com/jirokasimu');

  const result = await page.evaluate(() =>
    new Date().toLocaleTimeString('en-GB', { timeZoneName: 'short' })
  );

  await browser.close();

  return result;
};

if (require.main === module) {
  index()
    .then((result) => console.log(result))
    .catch((err) => console.log(err));
}

module.exports = { index };
```

Same thing goes for `languages`, `userAgent`, `webdriver`, etc.

**Comment by tmeasday** [comment]
Thanks for the fast turnaround and great work in general @alixaxel -- much appreciated.
