### ISSUE TITLE
Consider providing shared AWS Lambda Layers please

### ISSUE THREAD

**Issue by zombie** [alixaxel/chrome-aws-lambda#20]
Since you already provide instructions for creating a lambda layer (thank you!), how about uploading one public layer for everyone to use, and listing it at [λ A curated list of awesome AWS Lambda Layers](https://github.com/mthenw/awesome-layers). 

That would save everyone having to create and upload their own version (and especially Windows users).

I think one upload per release/tagged version should be enough (so ~once per month), anyone who needs daily updates could do it themselves.

**Comment by zombie** [comment]
Forgot to mention, perhaps having an unpacked version of the layer would also make sense, since it should be within the Lambda limits ([currently 250M](https://docs.aws.amazon.com/lambda/latest/dg/limits.html)), and could save on extracting at run time for (cold) startups.

**Comment by alixaxel** [comment]
Regarding your last comment, I'm considering it (see [my comment here](https://github.com/alixaxel/chrome-aws-lambda/issues/22#issuecomment-468926289)).

As for your initial request, I'm not sure if Layers need to be deployed to all the regions in order to achieve maximum fetch performance (my uneducated guess, would be that they need). I was waiting for Terraform to add support to AWS Lambda Layers to address this and be able to automatically publish Layers in all the regions, but there's also an additional annoyance which is the discrepancy between Layer versions and the version of this package. I need to ponder this for a while longer before I commit to providing the layer.

**Comment by dattto** [comment]
@alixaxel isn't puppeteer's bundled uncompressed chrome on linux 280M? that's over the lambda layer limit.

**Comment by alixaxel** [comment]
@dattto The one bundled by puppeteer might be, I haven't checked in a while.

But the headless build I provide on [`/bin`](https://github.com/alixaxel/chrome-aws-lambda/tree/master/bin) is roughly 125MB uncompressed.

**Comment by dattto** [comment]
maintaining a layer and its versioning in addition to this project adds an unnecessary overhead and will confuse users. I prefer to built my own layers and I'm sure others don't want to rely on a public layer that can disappear on any given day. 

Offering it uncompressed is a good idea.

**Comment by alixaxel** [comment]
@datto I lean towards that opinion as well. Regarding offering the binary uncompressed, GitHub as a hard limit on file sizes (100MB). Decompressing the file is pretty straightforward though:

```
brotli -d bin/*.br
```

**Comment by dattto** [comment]
Thanks, github's file limit is a bummer. Removing dependencies and improving lambda startup time is already appreciated 👍

**Comment by zombie** [comment]
> I'm sure others don't want to rely on a public layer that can disappear on any given day.

Meh, from the AWS docs:

"The creator of a layer can delete the version of the layer that you're using. When this happens, your function continues to run as though the layer version still existed."

So a worst case scenario: only when you need to update the layer configuration will you need to find another solution -- the current solution.

**Comment by zombie** [comment]
And the link from the first comment [λ A curated list of awesome AWS Lambda Layers](https://github.com/mthenw/awesome-layers) shows people want and do depend on layers built by strangers.

**Comment by dattto** [comment]
@zombie, I believe that puppeteer is still in early development stage. If you go to their issues page you will see that even the smallest build change in chrome's binary sometimes breaks their API or a bug that caused packaging the wrong chrome version. Updating layers becomes a maintenance job, at least until v2.0.

**Comment by zombie** [comment]
That's a real shame, but thanks for doing all the legwork!

> Specifically, I want to understand if you think `puppeteer-core` should be packaged in the same Layer or not? I could imagine publishing a Layer tracking Chromium revisions, but with PPTR too it gets trickier.

That was my idea, since the versions are tied together (and there seem to be <2 releases per month), but I can see how that might be too much, especially across all regions. :/

**Comment by alixaxel** [comment]
@zombie I've decided that maintaining Layers and tracking puppeteer itself would be too much of an hassle for me to commit to, at least for now. I did however, update the [Layer instructions](https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer) so that `puppeteer-core` is also bundled in the same layer - at least it's a little bit more convenient!
