### ISSUE TITLE
[BUG] Install size too big for AWS Lambda limit

### ISSUE THREAD

**Issue by shaneosullivan** [alixaxel/chrome-aws-lambda#200]
## Environment
* `chrome-aws-lambda` Version: 8.0.0
* `puppeteer` / `puppeteer-core` Version:
* OS: 
* Node.js Version: 
* Lambda / GCF Runtime: 

## Expected Behavior

It should be possible to install recent versions on AWS Lamda without going over the 50MB limit

## Current Behavior

The install size is up to 47MB (see https://packagephobia.com/result?p=chrome-aws-lambda@8.0.0), which leaves almost no space for any other code in order to fit inside the 50MB limit on AWS Lambda.

## Steps to Reproduce

Run a build and look at the bundled file sizes

-->

## Possible Solution

It seems that almost all the required size comes from the single bundled Chromium binary.  Are there any build flags that could be used to remove unnecessary features and shrink that file by 10MB or more, to leave room for other code to run?

**Comment by bestplay9384** [comment]
Just push it to the AWS Lambda Layer then :)

There is no possibility in endless "shrinking" the size, because it mainly comes with chromium binary itself - it is being updated and its size continue to grow...
Brotli algorithm used to pack it all is made by Google, it looks quite great, especially in compression level, i think there isn't much more here we can do :/

**Comment by shaneosullivan** [comment]
I'm working with Vercel, which does not give direct access to the AWS Lambda deployment that they use.
I can of course choose to deploy a standalone service for just the part of my application that needs Puppeteer, but that adds  a lot of complexity that it would be ideal to avoid if at all possible.

With the direction it is going (47MB and counting) this package will soon not be usable at all on AWS Lambda, so either that's acceptable and there's nothing to be done, or there is a possibility of engaging with the Chromium team to see if any build flags exist/could be added for a stripped down build intended for deployment to the cloud

**Comment by alixaxel** [comment]
@shaneosullivan This was a concern of mine as well, but somewhat alleviated with the introduction of AWS Layers.

The referenced Chromium build has been steadily increasing at around 0.5MB (compressed) per release, on average.

That I know of, there's little room for improvement:

- Dropping [SwiftShader (~1MB)](https://github.com/alixaxel/chrome-aws-lambda/blob/master/bin/swiftshader.tar.br), which will affect some GPU-related flags and functionality.
- Shipping without [Open Sans (~0.5MB)](https://github.com/alixaxel/chrome-aws-lambda/blob/master/bin/aws.tar.br), which will affect any sort of text rendering.

The above potential compromises would yield only marginal breathing room and would not be worth it over time.

I also explored all the Chromium build flags some time ago and there was nothing that could be done to shrink it further.

Seems to me that it would be easier if Vercel supported Lambda Layers somewhere in their deployment specification.

**Comment by ryantando** [comment]
@shaneosullivan I'm also using vercel, have you fpound any solution on this?

**Comment by shaneosullivan** [comment]
Unfortunately not. My hack around it was to set up a standalone VM and run
a node server on it that runs all of the APIs I need that use Chrome, while
keeping all other APIs on Vercel. It’s a mess but it works

**Comment by ryantando** [comment]
Thanks for your reply. I just set up also my own to a node server.
Will probably try lambda future in near future to see how it compares to node server

> Unfortunately not. My hack around it was to set up a standalone VM and run a node server on it that runs all of the APIs I need that use Chrome, while keeping all other APIs on Vercel. It’s a mess but it works
> […](#)
> On Mon 31 May 2021 at 15:38, Ryan Tando ***@***.***> wrote: @shaneosullivan <https://github.com/shaneosullivan> I'm also using vercel, have you fpound any solution on this?

**Comment by keiraarts** [comment]
Had a similar issue, solved by downgrading my package to 5.4.0 which shipped a much smaller instance of Chrome.

**Comment by transitive-bullshit** [comment]
I ran into this as well. Some steps for others to help debug the issue:

- Ensure tree shaking is working properly and make sure your serverless function imports are as minimal as possible
- Ensure large third-party libraries have `"sideEffects": false` in their package.json (otherwise vercel's bundler may be forced to include them in your lambda even if they're not used)

Even with these changes, the current compressed size of `chrome-aws-lambda` is really close to the Vercel / AWS limit at **49.7MB**. If this is the case for you, then consider downgrading to an earlier version of `chrome-aws-lambda`, some of which are much smaller.

- [chrome-aws-lambda v10.1.0](https://www.npmjs.com/package/chrome-aws-lambda/v/10.1.0) - **49.7MB**
- [chrome-aws-lambda v2.1.1](https://www.npmjs.com/package/chrome-aws-lambda/v/2.1.1) - **43.3MB**
- [chrome-aws-lambda v1.6.3](https://www.npmjs.com/package/chrome-aws-lambda/v/1.6.3) - **34.9MB**

**Comment by harisvsulaiman** [comment]
i recently hit this limitation on vercel, turns out its pretty easy go over the 50mb limit.

**Comment by offero** [comment]
I'm considering just switching to AWS at this point since I can't customize the lambda or use the layers on vercel.

**Comment by pencilcheck** [comment]
Anyone who are using the older version and want a type def file come visit this link:
https://gist.github.com/rohmanhm/5bf4be5e969250eb6fde558117f4e742

See my comment (at the very bottom) of the version for pupeteer-core with typescript 8+ support

**Comment by styfle** [comment]
Since several people here ran into this size issue when trying to generate OG Images on Vercel, I want to point out there is a new package designed to solve this specific problem: `@vercel/og`

https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images

**Comment by pencilcheck** [comment]
version 6.0.0 + node14 worked for me
