### ISSUE TITLE
How do you generate these binaries? 

### ISSUE THREAD

**Issue by govindrai** [alixaxel/chrome-aws-lambda#22]
Hi Alix!

Thanks a lot for your contributions to this project! I am able to use your binaries, but I am wondering how you are generating these binaries in the first place? Is there a chromium page where you can specify a configuration and it will generate the right chromium binary for you? I think this would be a helpful addition to the readme as it wont leave your users in the dark in the event it becomes hard for you to generate the binaries. Plus the community can help you out as well.

Also there is an opportunity for improvement in your readme documentation under the Lambda section where you can update the commands for uncompressing the `.br` binary and then zipping it up as a layer that can then be uploaded to lambda (currently it shows an example for tarballs).

Thanks,
Govind

**Comment by alixaxel** [comment]
Hey @govindrai, from day one I've been including the [compilation instructions in the README](https://github.com/alixaxel/chrome-aws-lambda#compiling) and the [automated Ansible playbook](https://github.com/alixaxel/chrome-aws-lambda/blob/master/_/ansible/plays/chromium.yml) to compile it is published as well. Regarding your other point:

> Also there is an opportunity for improvement in your readme documentation under the Lambda section where you can update the commands for uncompressing the .br binary and then zipping it up as a layer that can then be uploaded to lambda (currently it shows an example for tarballs).

This is not quite right, the part where it untars is related to the (necessary) previous `npm pack` step.

I thought about not using Brotli to compress the Chromium binary so that it could be uploaded as a Lambda Layer, but the code itself will need to be refactored to allow for this, namely this snippet:

https://github.com/alixaxel/chrome-aws-lambda/blob/f91f050419b79f3f364160c8a2695c9f1f39e4d4/source/index.js#L89-L106

It may come in the future, but for now it's not as simple as uncompressing the binary and uploading it.
