### ISSUE TITLE
[QUESTION] Inflation takes much longer than the README indicates

### ISSUE THREAD

**Issue by ericmacfarland** [alixaxel/chrome-aws-lambda#228]
## Environment
* `chrome-aws-lambda` Version: 10.0.0
* `puppeteer` / `puppeteer-core` Version: 10.1.0
* OS: MacOS
* Node.js Version: 14.x
* Lambda / GCF Runtime: `nodejs14.x`

## Expected Behavior

The compressed binary should be inflated in ~700ms as documented in the README and [#44](https://github.com/alixaxel/chrome-aws-lambda/issues/44#issuecomment-496853654).

## Current Behavior

It takes more than 10s for the binary to be inflated.
![image](https://user-images.githubusercontent.com/26652326/124818999-4d683a80-df31-11eb-88d3-332661e994e5.png)
![image](https://user-images.githubusercontent.com/26652326/124818923-345f8980-df31-11eb-9457-a4c387247b51.png)

## Steps to Reproduce

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    console.time('bootstrap');
    const executablePath = await chromium.executablePath;
    console.timeEnd('bootstrap');
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page = await browser.newPage();

    await page.goto(event.url || 'https://example.com');

    result = await page.title();
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

**Comment by ericmacfarland** [comment]
I did notice that my lambda was reporting using all of its allocated memory, but even after increasing the memory allocation the inflation still takes ~6s in my Lambda

**Comment by alixaxel** [comment]
@ericmacfarland The ~700ms figure is merely indicative for comparison between different compression algorithms. 

A couple things to take into consideration regarding that benchmark:

1. the inflation benchmark was executed on my local environment and not on Lambda, Lambda is likely slower
2. the initial Chromium 64.0 compressed size was [30MB](https://github.com/alixaxel/chrome-aws-lambda/blob/v0.13.0/bin/chromium-64.0.3264.0.br) vs [45MB](https://github.com/alixaxel/chrome-aws-lambda/blob/v10.0.0/bin/chromium.br) for current Chromium 92.0
3. [SwiftShader](https://github.com/alixaxel/chrome-aws-lambda/blob/v10.0.0/bin/swiftshader.tar.br) is also bundled and inflated since version 1.15.0
4. [since `AWS_Lambda_nodejs10.x`](https://github.com/alixaxel/chrome-aws-lambda/issues/37), the Lambda environment needs [additional libraries and fonts](https://github.com/alixaxel/chrome-aws-lambda/blob/v10.0.0/bin/aws.tar.br) to run properly

That being said, with a freshly deployed Lambda I get the following timings for `executablePath`, using the following code:

```js
console.time(`executablePath (${process.env.AWS_LAMBDA_FUNCTION_MEMORY_SIZE} MB)`);
let executablePath = await chromium.executablePath;
console.timeEnd(`executablePath (${process.env.AWS_LAMBDA_FUNCTION_MEMORY_SIZE} MB)`);
```

The first execution for each is always a cold start, followed by a warmed up invocation:

- executablePath (200 MB): 15.068s
- executablePath (200 MB): 0.22ms
- executablePath (256 MB): 11.441s
- executablePath (256 MB): 0.121ms
- executablePath (384 MB): 7.977s
- executablePath (384 MB): 0.133ms
- **executablePath (512 MB): 6.259s**
- executablePath (512 MB): 0.125ms
- executablePath (768 MB): 3.930s
- executablePath (768 MB): 0.296ms
- executablePath (1024 MB): 3.178s
- executablePath (1024 MB): 0.114ms
- executablePath (1536 MB): 2.668s
- executablePath (1536 MB): 0.118ms
- **executablePath (1600 MB): 2.593s**
- executablePath (1600 MB): 0.131ms
- executablePath (2048 MB): 2.387s
- executablePath (2048 MB): 0.263ms
- executablePath (4096 MB): 2.162s
- executablePath (4096 MB): 0.13ms
- executablePath (8192 MB): 2.116s
- executablePath (8192 MB): 0.112ms

As the README states:

> You should allocate at least 512 MB of RAM to your Lambda, however 1600 MB (or more) is recommended.

Some fluctuation is expected, but I assume you deployed your Lambda with 256MB initially and then doubled to 512MB?

**Comment by ericmacfarland** [comment]
> The inflation benchmark was executed on my local environment and not on Lambda, Lambda is likely slower

Ah, understood, thanks for clarifying that point! I think that's where my confusion stemmed from.

> A couple things to take into consideration regarding that benchmark

These are all very helpful, thanks for the additional context!

> Some fluctuation is expected, but I assume you deployed your Lambda with 256MB initially and then doubled to 512MB?

You're correct, I started with 256MB and then doubled to 512MB. I ended up settling on 1024MB. Based on my testing (confirmed by your stats above as well), the speed boost starts to drop off rather quickly above ~1024MB.

I'll go ahead and close this, thanks for the fast reply and all of the helpful info!
