### ISSUE TITLE
Can I use this library with selenium-webdriver as well? Instead of using Puppeteer.

### ISSUE THREAD

**Issue by eliteluxury** [alixaxel/chrome-aws-lambda#35]
Thanks for this library.
I'd like to know if I can use this library with selenium-webdriver.

**Comment by alixaxel** [comment]
I don't know because I'm not familiar with `selenium-webdriver`.

I'm assuming all it requires is the path to the headless Chromium binary, if so you can try this:

```js
const pathToHeadlessChromium = await (require('chrome-aws-lambda').executablePath);
```

Should do the trick. You might need to use some of the [default provided `args`](https://github.com/alixaxel/chrome-aws-lambda/blob/669fff2665f559f52cfd57b1a5162ba68324d6bc/source/index.js#L56-L114) as well.
