### ISSUE TITLE
Better usage documentation

### ISSUE THREAD

**Issue by SaltedBlowfish** [alixaxel/chrome-aws-lambda#40]
As a developer, I rely on clear and concise usage documentation when installing and (properly) using a package. The example in the readme is great, but, there should be clear documentation on setting up the `serverless.yml` file to properly utilize this package as a layer.

Also, unless the binaries shipped with this package are added to the `package:exclude` `serverless.yml` section, then the Lambda function still contains a massive binary. This should be made clear to other developers in the documentation, along with what else can be excluded from your package to optimize Lambda size.

As a starting point, here is what I did to get this package working for myself:

1. Put built layer zip into a folder in your project:

![image](https://user-images.githubusercontent.com/6200478/58233956-3c78f280-7cf2-11e9-99ee-35a57a9d182c.png)

2. Setup Lambda layer in `serverless.yml` to use zip:

```
layers:
  chrome:
    path: layer
```

3. Add new layer to the function you need it in:

```
functions:
  yourFunctionName:
    ...
    layers:
      - {Ref: ChromeLambdaLayer}
```

4. Tell serverless not to include it in your actual Lambda function:

```
package:
  exclude:
    - node_modules/chrome-aws-lambda/bin/**
```

**Comment by mrweir** [comment]
I'd also like to share the process I used, as I went with a slightly different deployment scheme than @SaltedBlowfish, and it did take a bit of playing around for me to get it all working.

I chose to create my lambda layer separately (via the console) as I didn't want it connected directly to my serverless deployment, since I plan to re-use the layer in other stacks.

1. Followed the [AWS Lambda Layer](https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer) instructions to create the chrome_aws_lambda.zip file.
2. Used the AWS console to create a new layer using that zip file
3. Added that layer by ARN to the function I needed it in:
```yaml
functions:
  yourFunctionName:
    #...
    layers:
      - <layer ARN here>
```
4. I'm also using webpack, so I had to add puppeteer-core and chrome-aws-lambda to my [webpack externals configuration](https://webpack.js.org/configuration/externals/) to avoid errors in my build process:
```javascript
module.exports = {
  //...
  externals: ["puppeteer-core", "chrome-aws-lambda"]
};
```

**Comment by SaltedBlowfish** [comment]
@mrweir This is great! Thanks for adding those details.

**Comment by alixaxel** [comment]
@SaltedBlowfish

It seems like you're looking for documentation regarding integration with `serverless` framework.

Personally, I use Terraform to manage my stack.
Like me, there are other people who prefer to use any of the following frameworks (in JS land alone):

- Apex
- Up
- SAM
- Claudia
- ...

I simply cannot provide support/documentation for all of them.
