### ISSUE TITLE
slow as hell

### ISSUE THREAD

**Issue by whatsdis** [alixaxel/chrome-aws-lambda#44]
the same function takes less than 4 seconds locally

yet even with using layers, it takes 12 seconds. 3X slowdown when deployed on AWS Lambda.

**Comment by alixaxel** [comment]
@whatsdis You should know that there's a 700/800 ms overhead for cold functions.

That being said, it's quite normal for Lambdas to be slower than your local machine, a 3x slowdown seems like a bit too much, but in order to properly look into it, you should share your function (or at least a outline of what it's doing) as well as Lambda region, RAM allocation and the specs of your local machine.

I'm closing this as non-actionable for now, feel free to add more details and I will reopen.
