### ISSUE TITLE
chrome.executablePath is returning null

### ISSUE THREAD

**Issue by zeeshanaligold** [alixaxel/chrome-aws-lambda#46]
Have problem with executablePath. It's returning null. 

```
const browser = await puppeteer.launch({
      args: chrome.args,
      headless: chrome.headless,
      executablePath: await chrome.executablePath,
})
```

**Comment by andihub** [comment]
Same problem here on local env.
Seems like it's looking for `/tmp/chromium` but this is 0KB.
I tried `cp node_modules/chrome-aws-lambda/bin/chromium-72.0.3617.0.br /tmp/chromium` .
For `chrome.headless` to return `true` I have to set `AWS_LAMBDA_FUNCTION_NAME` env to some dummy value.
But then when trying to spawn the process something doesn't work. I get `input.on is not a function` in `waitForWSEndpoint` because `chromeProcess.stderr` is `undefined`

**Comment by zeeshanaligold** [comment]
@andihub 
chrome.executablePath was null because chrome.headless is false. In order to make it work for local testing purposes, you have to make sure one of these ['AWS_LAMBDA_FUNCTION_NAME', 'FUNCTION_NAME', 'FUNCTION_TARGET'] environment variables are set.

**Comment by alixaxel** [comment]
@andihub @zeeshanaligold This might help:

https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development
