### ISSUE TITLE
Flags for improving text rendering

### ISSUE THREAD

**Issue by Kikobeats** [alixaxel/chrome-aws-lambda#51]
Hello,

I noted some text rendering is inconsistent compared with doing the same but using a local process.

This is a screenshot done by my service running locally:

![download (1)](https://user-images.githubusercontent.com/2096101/61492775-4f3a3b80-a9b2-11e9-94ce-1b84c11fbea8.png)

and that's exactly the same but running at AWS Lambda using this project:

![download](https://user-images.githubusercontent.com/2096101/61492814-5f521b00-a9b2-11e9-94e5-de1c70fc092c.png)

As you can appreciate, the text looks a bit spaced.

I saw this is a recurrent issue opened at puppeteer repository: https://github.com/GoogleChrome/puppeteer/issues/2410

Based on the suggestions, I tried some multiple flags combinations that currently are not present as default args:

```
'--font-render-hinting=medium' // could be 'none', 'medium'
'--enable-font-antialiasing'
```

None of these combinations had a successful output yet, but happy if we can use to try different approaches in order to normalize how text is rendering 🙂

**Comment by alixaxel** [comment]
Hey @Kikobeats, I suspect that the issue here is not with the font rendering but rather with the font itself: Lambda only ships with the DejaVu font family, depending on the font face Twitter is using and which font families are available on your local system, that could very well explain the visual differences.

I will try to reproduce/confirm this over the weekend though.

**Comment by Kikobeats** [comment]
this is the font family shipped by Twitter:

```
font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu, "Helvetica Neue", sans-serif;
```

**Comment by Kikobeats** [comment]
Not sure if this could be related: https://github.com/GoogleChrome/puppeteer/issues/2692#issuecomment-414319342

**Comment by alixaxel** [comment]
@Kikobeats Because this is likely system-dependent, could you confirm something for me?

If you browse to https://twitter.com/ProductHunt/status/1153402334447362048, and then inspect the "Community managers rejoice!" (`.js-tweet-text-container`) node and go all the way to the bottom of the **Computed** tab - which rendered font do you see there?

![image](https://user-images.githubusercontent.com/262782/61692104-edb4fc80-ad24-11e9-881f-e6fe2720e003.png)

The original CSS for the font-family is:

```css
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
```

In my case (Ubuntu Linux) it's falling back to the generic `sans-serif` font `Liberation Sans`.

If I manually override the CSS to `font-family: "DejaVu Sans";` ([download](https://dejavu-fonts.github.io/)) this is what I get:

![image](https://user-images.githubusercontent.com/262782/61692433-8b103080-ad25-11e9-8dc6-f9259880ae29.png)

If you look at the `m` closely and the overall spacing, you can see that it matches the look you get on Lambda. So the behavior seems consistent for me on local, I would say this is simply a font-face issue.

**Comment by Kikobeats** [comment]
you're totally right! The thing is happening is my production scenario doesn't have the same font than my local, so I need to put there some fallbacks font in order to use them and have the same look and feel 🙂

Thanks for spend time on this!
