### ISSUE TITLE
Failed to create/find /tmp/swiftshader folder, crashes browser instance

### ISSUE THREAD

**Issue by rnnc** [alixaxel/chrome-aws-lambda#59]
## Environment
* `chrome-aws-lambda` Version: 1.19.0
* `puppeteer` / `puppeteer-core` Version: 1.19.0
* OS: Windows 10
* Node.js Version: 12.9.0
* Lambda / GCF Runtime: Local Dev

What shows in console

(node:15684) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir '/tmp/swiftshader'
    at mkdirSync (fs.js:806:3)
    at Function.get executablePath [as executablePath] (C:\Users\{directory}\node_modules\chrome-aws-lambda\source\index.js:150:7)

```
    if (existsSync('/tmp/swiftshader') !== true) {
      mkdirSync('/tmp/swiftshader'); // points here here specifically
    }
```

It also points to this piece of code while launching puppeteer-core

```
const browser = await puppeteer.launch({
    args: chrome.args,
    executablePath: await chrome.executablePath, // here
    headless: chrome.headless
  });
```

What could be happening here? mkdirSync not making the folder? Why?

I've also used node 8.10 via nvm and that shows pretty much the same error; 

Any help is appreciated

**Comment by alixaxel** [comment]
@rnnc Are you setting any environment variables?

**Comment by rnnc** [comment]
@alixaxel yes, I have an env file and i'm setting the variables

```
AWS_EXECUTION_ENV = "AWS_Lambda_nodejs8.10"
AWS_LAMBDA_FUNCTION_NAME = "DEV_BOT"
```

**Comment by alixaxel** [comment]
@rnnc What is happening is that by using these environment variables, you are effectively "tricking" the package into thinking it's operating under AWS Lambda environment - but your real environment is totally incompatible with it, so you end up with these error messages.

Among other things, the Lambda environment is using Amazon **Linux**, which due to being Linux, has a `/tmp` directory structure - unlike Windows. Another important difference is that both the Chromium binary and SwiftShader libraries are _specifically_ compiled for this specific (Linux) environment - which is the main purpose of this package - and they will never run on Windows. I suggest you follow the approach recommended in the [Local Development Wiki page](https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development), specifically the "[Workaround](https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development#workaround)" section.
