### ISSUE TITLE
Support local execution for testing by default

### ISSUE THREAD

**Issue by cschmidt** [alixaxel/chrome-aws-lambda#7]
It's nice to be able to test your Lambda function in a local, Lambda-like environment as you're developing.

However, currently there's a check for whether or not you're running in Lambda (https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js#L91), and you get the following error when you try to run locally:

    Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

Just faking out the check for headless (doing `export AWS_LAMBDA_FUNCTION_NAME=myLambdaFunc` or `process.env.AWS_LAMBDA_FUNCTION_NAME = 'myLambdaFunc'`) makes everything work nicely, assuming you're running on a Lambda-like host environment.

Thoughts on just removing the check for headless?

**Comment by alixaxel** [comment]
@cschmidt So the reason why this check is in place is due to the Chromium binary itself. Chromium is statically compiled on a 64bit Amazon Linux instance, to ensure compatibility with AWS Lambda.

If this check was removed, and under certain systems, it simply wouldn't start. So I can't get away with it.

There's two solutions for this:

1. use `puppeteer` on dev and `puppeteer-core` on production
2. fake the `AWS_LAMBDA_FUNCTION_NAME` environment variable like you're doing (might not work)

For the first option, you would install dependencies like this:

```shell
npm install puppeteer --save-dev
npm install puppeteer-core --save-prod
```

And then you can conditionally require the puppeteer package like this:

```javascript
const chromium = require('chrome-aws-lambda');
const puppeteer = chromium.puppeteer;

exports.handler = async (event, context) => {
  let browser = await puppeteer.launch({
    args: chromium.args,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
  });

  // ...
};
```

The getter is simply a try catch block that falls back to `puppeteer-core` if `puppeteer` is not present:

https://github.com/alixaxel/chrome-aws-lambda/blob/eeeca36782738bdd25f6b4d8061d4937501e1f91/source/index.js#L165-L175

Just make sure that you skip `devDependencies` when deploying to production:

```shell
npm install --no-optional --no-shrinkwrap --production && npm dedupe --no-shrinkwrap
```

---

PS: Sorry for the delay in the reply.

**Comment by oravecz** [comment]
[Serverless](https://serverless.com) is a popular tool for developing AWS functions, and I am using it in conjunction with `chrome-aws-lambda`. Serverless provides the means of launching a lambda locally using a command line syntax such as:

```
sls invoke local --function my-function
```

This also fails to launch puppeteer due to the fact that `AWS_LAMBDA_FUNCTION_NAME` is set during the invocation in order to simulate the actual environment in AWS.

I am using this approach to support running commands locally using Serverless.
```
const chromiumOrig = require('chrome-aws-lambda');
const chromium = class ServerlessChromium extends chromiumOrig {
    static get headless() {
        return (process.env.IS_LOCAL) || (process.env.AWS_LAMBDA_FUNCTION_NAME !== undefined);
    }
}
```

The environment variable `IS_LOCAL` is set to true when running locally in serverless.

**Comment by alixaxel** [comment]
@oravecz Are you saying that when you run `sls invoke local` both `AWS_LAMBDA_FUNCTION_NAME` and `IS_LOCAL` are set?

**Comment by oravecz** [comment]
Yes. IS_LOCAL was added to serverless to programmatically detect `invoke local` scenarios.
https://github.com/serverless/serverless/issues/3639

**Comment by NathanielHill** [comment]
@alixaxel Awesome, thanks for already having a solution for this baked in!

One note, if you're doing something like PDF generation you probably just want to set `headless` to `true` as `chromium.headless` with this technique will return false on your local machine.
